sonar.projectKey=web-react-player
sonar.projectName=web-react-player
sonar.organization=NIKIRIKI7

# Пути к исходному коду библиотек
sonar.sources=packages/core/src,packages/ui/src

# Исключения из анализа (сборка, мусор, песочница, документация)
sonar.exclusions=**/dist/**,**/node_modules/**,apps/**,docs/**,**/*.api.md,repomix-*.xml

# Кодировка
sonar.sourceEncoding=UTF-8
sonar.javascript.environments=browser,node