sonar.organization=mcniki
sonar.projectKey=mcniki_web-react-player-monorepo

sonar.sources=packages
sonar.exclusions=**/dist/**,**/node_modules/**,**/*.d.ts,apps/playground/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info